apiVersion: v1
kind: ServiceAccount
metadata:
  name: checker
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checker-manager
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: checker
subjects:
- kind: ServiceAccount
  name: checker
roleRef:
  kind: ClusterRole
  name: checker-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: checker
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: checker
          containers:
          - name: checker
            image: anilkuscu/job.control
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
